# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# More versions available at: https://legacyfabric.net/usage.html
minecraft_version=1.8.9
feather_build=1
loader_version=0.18.3
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=net.inboundbark
archives_base_name=classiccaves

# Dependencies
# OSL
osl_version=0.17.1
# Legacy Fabric API
# Check availability for your MC version on [Modrinth](https://modrinth.com/mod/legacy-fabric-api/versions?l=ornithe)
legacy_fabric_version=1.16.0+1.8.9
